version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "v1.1.11"
    labels:
      - "🛍️ Scope : Dependencies"
      - "🚀 Type : Update"
      - "📦 Package : NPM"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "v1.1.11"
    schedule:
      interval: "daily"
    labels:
      - "🛍️ Scope : Dependencies"
      - "🚀 Type : Update"
      - "📦 Package : PIP"