/**
 *  @FileID          Types\Languages.ts
 *  @Description     Currently, there is no description available.
 *  @Author          @MeetBhingradiya
 *  
 *  -----------------------------------------------------------------------------
 *  Copyright (c) 2025 Meet Bhingradiya
 *  All rights reserved.
 *  
 *  This file is part of the @MeetBhingradiya's Portfolio project and is protected under copyright
 *  law. Unauthorized copying of this file, via any medium, is strictly prohibited
 *  without explicit permission from the author.
 *  
 *  -----------------------------------------------------------------------------
 *  @created 13/01/25 11:34 AM IST (Kolkata +5:30 UTC)
 *  @modified 14/01/25 3:22 PM IST (Kolkata +5:30 UTC)
 */

export enum Languages {
    Afrikaans = 'af',
    Albanian = 'sq',
    Amharic = 'am',
    Arabic = 'ar',
    Armenian = 'hy',
    Azerbaijani = 'az',
    Basque = 'eu',
    Belarusian = 'be',
    Bengali = 'bn',
    Bosnian = 'bs',
    Bulgarian = 'bg',
    Catalan = 'ca',
    Cebuano = 'ceb',
    Chichewa = 'ny',
    ChineseSimplified = 'zh-CN',
    ChineseTraditional = 'zh-TW',
    Corsican = 'co',
    Croatian = 'hr',
    Czech = 'cs',
    Danish = 'da',
    Dutch = 'nl',
    English = 'en',
    Esperanto = 'eo',
    Estonian = 'et',
    Filipino = 'tl',
    Finnish = 'fi',
    French = 'fr',
    Frisian = 'fy',
    Galician = 'gl',
    Georgian = 'ka',
    German = 'de',
    Greek = 'el',
    Gujarati = 'gu',
    HaitianCreole = 'ht',
    Hausa = 'ha',
    Hawaiian = 'haw',
    Hebrew = 'he',
    Hindi = 'hi',
    Hmong = 'hmn',
    Hungarian = 'hu',
    Icelandic = 'is',
    Igbo = 'ig',
    Indonesian = 'id',
    Irish = 'ga',
    Italian = 'it',
    Japanese = 'ja',
    Javanese = 'jv',
    Kannada = 'kn',
    Kazakh = 'kk',
    Khmer = 'km',
    Kinyarwanda = 'rw',
    Korean = 'ko',
    Kurdish = 'ku',
    Kyrgyz = 'ky',
    Lao = 'lo',
    Latin = 'la',
    Latvian = 'lv',
    Lithuanian = 'lt',
    Luxembourgish = 'lb',
    Macedonian = 'mk',
    Malagasy = 'mg',
    Malay = 'ms',
    Malayalam = 'ml',
    Maltese = 'mt',
    Maori = 'mi',
    Marathi = 'mr',
    Mongolian = 'mn',
    MyanmarBurmese = 'my',
    Nepali = 'ne',
    Norwegian = 'no',
    Odia = 'or',
    Pashto = 'ps',
    Persian = 'fa',
    Polish = 'pl',
    Portuguese = 'pt',
    Punjabi = 'pa',
    Romanian = 'ro',
    Russian = 'ru',
    Samoan = 'sm',
    ScotsGaelic = 'gd',
    Serbian = 'sr',
    Sesotho = 'st',
    Shona = 'sn',
    Sindhi = 'sd',
    Sinhala = 'si',
    Slovak = 'sk',
    Slovenian = 'sl',
    Somali = 'so',
    Spanish = 'es',
    Sundanese = 'su',
    Swahili = 'sw',
    Swedish = 'sv',
    Tajik = 'tg',
    Tamil = 'ta',
    Tatar = 'tt',
    Telugu = 'te',
    Thai = 'th',
    Turkish = 'tr',
    Turkmen = 'tk',
    Ukrainian = 'uk',
    Urdu = 'ur',
    Uyghur = 'ug',
    Uzbek = 'uz',
    Vietnamese = 'vi',
    Welsh = 'cy',
    Xhosa = 'xh',
    Yiddish = 'yi',
    Yoruba = 'yo',
    Zulu = 'zu'
}
