interface Controller_Response {
    /**
     * + 0 for Invalid or Failed Response
     * + 1 for Valid Action or Success Response
     */
    Status: 0 | 1;

    /**
     * Message for the Response that will be shown to the user
     */
    Message: string;

    /**
     * Redirect or Action Code used by the client to perform REDIRECTs on Client Side
     */
    StatusCode: number | string;

    /**
     * Signature string that Client will use to verify the response data integrity
     * + It will be generated by the server and will be unique for each response
     * + Prevents the data tampering on response
     */
    Signature?: string;

    /**
     * Data to client Requested By Client
     */
    Data?: any;

    /**
     * Debug Information for the developers only Shown in Development Mode
     */
    Debug?: any;

    /**
     * Browser Status Code to Determine the Response is Success or Failure
     * + It will be 200 even if the response is failed or invalid so we not need to handle the error handling in the client side
     */
    StatusNumber?: number;

    /**
     * Status Text for the Browser Status Code Just like OK, Not Found, etc.
     */
    StatusText?: string;
}

export type { Controller_Response };
